### ISSUE TITLE
Is this org still functional? Can be joined?

### ISSUE THREAD

**Issue by itsN1X** [Quora-Users/quora-best-questions#2]

**Comment by kratsg** [comment]
Technically, it is still functional. I think we've just lost motivation to continue. Did you want to join?

**Comment by m1guelpf** [comment]
@kratsg Maybe we could use Orgmanager... https://orgmanager.miguelpiedrafita.com

**Comment by itsN1X** [comment]
That'd great. @kratsg

**Comment by itsN1X** [comment]
✅♻
